services:
  - type: web
    name: capital-management
    env: node
    plan: free
    buildCommand: sh -c 'npm install && npm run init-db'
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
